trigger: none
#- master

resources:
- repo: self

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage : Build_Push_and_Deploy_application
  jobs:
  - job: Build
    displayName: 'Build, push and deploy'
    steps:
      
      - task: Docker@2
        inputs:
          containerRegistry: 'prunedgecrConnection'
          repository: 'prunedgeimagerepo'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
      - task: AzureCLI@2
        displayName: 'Docker Image Deploy'
        inputs:
          azureSubscription: 'prunedgeServiceConnection'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az webapp config container set --name $(webAppName)\
              --resource-group $(resourceGroupName)\
              --docker-registry-server-url $(registryURL)\
              --docker-registry-server-user $(registryUser)\
              --docker-registry-server-password $(registryPass)\
              --docker-custom-image-name $(imageName)